/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardCustomerRouteImport } from './routes/dashboard.customer'
import { Route as DashboardDispatcherRouteImport } from './routes/dashboard.dispatcher'
import { Route as DashboardManagerRouteImport } from './routes/dashboard.manager'
import { Route as DashboardTechnicianRouteImport } from './routes/dashboard.technician'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCustomerRoute = DashboardCustomerRouteImport.update({
  id: '/dashboard/customer',
  path: '/dashboard/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDispatcherRoute = DashboardDispatcherRouteImport.update({
  id: '/dashboard/dispatcher',
  path: '/dashboard/dispatcher',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManagerRoute = DashboardManagerRouteImport.update({
  id: '/dashboard/manager',
  path: '/dashboard/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTechnicianRoute = DashboardTechnicianRouteImport.update({
  id: '/dashboard/technician',
  path: '/dashboard/technician',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/dispatcher': typeof DashboardDispatcherRoute
  '/dashboard/manager': typeof DashboardManagerRoute
  '/dashboard/technician': typeof DashboardTechnicianRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/dispatcher': typeof DashboardDispatcherRoute
  '/dashboard/manager': typeof DashboardManagerRoute
  '/dashboard/technician': typeof DashboardTechnicianRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/dispatcher': typeof DashboardDispatcherRoute
  '/dashboard/manager': typeof DashboardManagerRoute
  '/dashboard/technician': typeof DashboardTechnicianRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/customer'
    | '/dashboard/dispatcher'
    | '/dashboard/manager'
    | '/dashboard/technician'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/customer'
    | '/dashboard/dispatcher'
    | '/dashboard/manager'
    | '/dashboard/technician'
  id:
    | '__root__'
    | '/'
    | '/dashboard/customer'
    | '/dashboard/dispatcher'
    | '/dashboard/manager'
    | '/dashboard/technician'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardCustomerRoute: typeof DashboardCustomerRoute
  DashboardDispatcherRoute: typeof DashboardDispatcherRoute
  DashboardManagerRoute: typeof DashboardManagerRoute
  DashboardTechnicianRoute: typeof DashboardTechnicianRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/customer': {
      id: '/dashboard/customer'
      path: '/dashboard/customer'
      fullPath: '/dashboard/customer'
      preLoaderRoute: typeof DashboardCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/dispatcher': {
      id: '/dashboard/dispatcher'
      path: '/dashboard/dispatcher'
      fullPath: '/dashboard/dispatcher'
      preLoaderRoute: typeof DashboardDispatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manager': {
      id: '/dashboard/manager'
      path: '/dashboard/manager'
      fullPath: '/dashboard/manager'
      preLoaderRoute: typeof DashboardManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/technician': {
      id: '/dashboard/technician'
      path: '/dashboard/technician'
      fullPath: '/dashboard/technician'
      preLoaderRoute: typeof DashboardTechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardCustomerRoute: DashboardCustomerRoute,
  DashboardDispatcherRoute: DashboardDispatcherRoute,
  DashboardManagerRoute: DashboardManagerRoute,
  DashboardTechnicianRoute: DashboardTechnicianRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
